### ISSUE TITLE
high cpu usage when using `- MAX_RETRIES=0`

### ISSUE THREAD

**Issue by aniel300** [sonroyaalmerol/m3u-stream-merger-proxy#197]
i have notice when i use `- MAX_RETRIES=0` there is an unusual cpu usage, any thoughts?

**Comment by aniel300** [comment]
@sonroyaalmerol trying ur new image at the moment. seem to be working although i did catch this in the logs
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5fe772]
goroutine 54271 [running]:
bufio.(*Writer).Flush(0x466545?)
	/usr/local/go/src/bufio/bufio.go:633 +0x12
net/http.(*chunkWriter).flush(0x40b2ff?)
	/usr/local/go/src/net/http/server.go:403 +0x39
net/http.(*response).FlushError(0xc0004600e0)
	/usr/local/go/src/net/http/server.go:1773 +0x51
net/http.(*response).Flush(0xaeed10?)
	/usr/local/go/src/net/http/server.go:1765 +0x13
m3u-stream-merger/proxy.(*StreamInstance).ProxyStream.func2()
	/app/proxy/proxy_stream.go:87 +0x63
m3u-stream-merger/proxy.(*StreamInstance).ProxyStream(0xc005c620c0, {0x8abc20, 0xc000410cd0}, 0x0, 0xc0000c6000, 0xc001b79040, {0x8ab0a8, 0xc0004600e0}, 0xc000ae90a0)
	/app/proxy/proxy_stream.go:143 +0xb2a
created by m3u-stream-merger/handlers.StreamHandler in goroutine 3512
	/app/handlers/stream_handler.go:80 +0x6fe
```

**Comment by sonroyaalmerol** [comment]
thanks! that panic should be fixed on the latest commit

**Comment by aniel300** [comment]
that fixed it, thank you.
